// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://immpwedepfpfixirbswc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbXB3ZWRlcGZwZml4aXJic3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTk1OTcsImV4cCI6MjA3MzQ3NTU5N30.Qvaod9ccnQUmQBWgO2caEYnwzpb0BxCyeBWU1EwJllY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});